services:
  tupload:
    build: .
    container_name: tupload-app
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tupload.rule=Host(`${DOMAIN:-your-domain.com}`)"
      - "traefik.http.routers.tupload.entrypoints=websecure"
      - "traefik.http.routers.tupload.tls=true"
      - "traefik.http.services.tupload.loadbalancer.server.port=6060"
      - "traefik.http.middlewares.tupload-strip.stripprefix.prefixes=/static"
      - "traefik.http.routers.tupload.middlewares=tupload-strip"

networks:
  traefik:
    external: true

