server:
  port: 6060
  host: "0.0.0.0"
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"

storage:
  path: "./uploads"

domain: "your-domain.com"